//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageDate { get; set; }
        public System.TimeSpan MessageTime { get; set; }
        public int GroupId { get; set; }
    
        public virtual MessagingGroup MessagingGroup { get; set; }
    }
}
